/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { WETH9, WETH9Interface } from "../../common/WETH9";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "wad",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "deposit",
    outputs: [],
    payable: true,
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class WETH9__factory {
  static readonly abi = _abi;
  static createInterface(): WETH9Interface {
    return new Interface(_abi) as WETH9Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): WETH9 {
    return new Contract(address, _abi, runner) as unknown as WETH9;
  }
}
